### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by mhrechkin** [nickolay-grechkin/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by KennyLVM** [comment]
LANGUAGES
ENGLISH, POLSKA

SKILLS
yrdenaardigniquenaxii
CHARACTER
INTROVERT GENEROSITY FAIRNESS CHARISMA CONFIDENCE KINDNESS ADVENTUROUS RESOURCEFULNESS

LIKES 
UNICORNS RYE VODKA SWORDS GWENT ROACH ANECDOTES MY GRAY HAIR PRISCILLA'S SONG

DISLIKES 
TELEPORTS DANDELION'S POEMS LIES HYPOCRISY SHORTAGE OF ORDERS

WANT 
FIND A PERMANENT JOBMASTER NEW SIGNSMORE UNIQUE CARDS IN GWENT DECKTO READ MOREIMPROVE EQUIPMENTLEARN MORE POTIONS AND OILS
