### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by mhrechkin** [nickolay-grechkin/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by KennyLVM** [comment]
https://www.facebook.com/Witcher-Geralt-622141921155616/
Gwynbleidd@gmail.com
https://www.instagram.com/geralt.the.monster.slayer/
https://twitter.com/riviawitcher
