### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by mhrechkin** [nickolay-grechkin/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by KennyLVM** [comment]
This World Doesn't Need A Hero. It Needs A Professional.  That world-famous monster hunter, the man known in Elder Speech as Gwynbleidd, or, in our younger (yet no less noble) tongue, as the White Wolf. For Geralt of Rivia is a truly exceptional individual. A brief encounter might tempt one to label him a mere swinger of swords, a simple monster-catcher, a rough-and-tumble practitioner of a dirty trade - but peer closer and you will soon discover he is a man of unplumbed depths, unique views and vast, world-spanning experience.
